#!/usr/bin/env python3
"""Generate the Paper Mario N64Recomp config from the decomp ELF.

Reads the ELF symbol table, computes sizes for zero-sized global FUNC symbols
(using the next symbol address in the same section), and emits the PaperPad
N64Recomp TOML config with function_sizes and dead-function ignores.
"""
import subprocess
import sys
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ELF = ROOT / "ref/papermario/ver/us/build/papermario.elf"
ROM = ROOT / "generated/rom/baserom.z64"
OUT = ROOT / "generated/aot/paper-mario-us.toml"

def read_symbols(elf: Path):
    """Return list of (value, size, type, bind, ndx, name) from the ELF."""
    out = subprocess.run(
        ["mips-linux-gnu-readelf", "-sW", str(elf)],
        capture_output=True, text=True, check=True,
    ).stdout
    symbols = []
    for line in out.splitlines():
        parts = line.split()
        if len(parts) < 8 or not parts[0].rstrip(":").isdigit():
            continue
        # Num Value Size Type Bind Vis Ndx Name
        value = int(parts[1], 16)
        size = int(parts[2], 16)
        typ, bind, ndx, name = parts[3], parts[4], parts[6], parts[7]
        symbols.append((value, size, typ, bind, ndx, name))
    return symbols

def section_for(ndx: str, elf: Path):
    out = subprocess.run(
        ["mips-linux-gnu-readelf", "-SW", str(elf)],
        capture_output=True, text=True, check=True,
    ).stdout
    sections = {}
    for line in out.splitlines():
        # -SW columns: [Nr] Name Type Addr Off Size ES Flg Lk Inf Al
        m = re.match(r"^\s*\[ *(\d+)\] (\S+) +\S+ +([0-9a-f]+) +[0-9a-f]+ +([0-9a-f]+)", line)
        if m:
            idx = int(m.group(1))
            name, addr, size = m.group(2), int(m.group(3), 16), int(m.group(4), 16)
            sections[idx] = (name, addr, size)
    return sections

def main():
    sections = section_for("", ELF)
    symbols = read_symbols(ELF)
    all_funcs = [s for s in symbols if s[2] == "FUNC"]
    funcs = [s for s in all_funcs if s[4].isdigit() and int(s[4]) in sections]
    # Dead/uncompiled functions are never called and must not be recompiled.
    # ABS-section dead symbols are already skipped during ELF load (they are not
    # in functions_by_name), so only dead symbols in real sections need ignores.
    ignores = sorted({s[5] for s in all_funcs
                      if s[5].startswith("dead_") and s[4].isdigit() and int(s[4]) in sections})
    # group by section, sort by address
    by_section = {}
    # Use every symbol (not only FUNC) to find where a function's code ends:
    # a size-0 function usually ends at the next symbol of any type in its
    # section. Over-reading past data produces garbage instructions.
    for value, size, typ, bind, ndx, name in symbols:
        if not ndx.isdigit() or int(ndx) not in sections:
            continue
        if value == 0 and typ == "SECTION":
            continue
        by_section.setdefault(int(ndx), []).append((value, size, name, bind, typ))

    sizes = []
    for ndx, sec_funcs in by_section.items():
        sec_name, sec_addr, sec_size = sections[ndx]
        sec_funcs.sort()
        for i, (value, size, name, bind, typ) in enumerate(sec_funcs):
            if size != 0:
                continue
            if name.startswith("._"):
                continue
            if typ != "FUNC":
                continue
            # next function address in same section (or section end)
            if i + 1 < len(sec_funcs):
                next_addr = sec_funcs[i + 1][0]
            else:
                next_addr = sec_addr + sec_size
            fsize = next_addr - value
            if fsize > 0 and fsize % 4 == 0:
                sizes.append((name, fsize))
            else:
                print(f"# warning: could not size {name} @ 0x{value:08X} (next 0x{next_addr:08X})", file=sys.stderr)

    # dedupe by name (keep first)
    seen = set()
    sizes_dedup = []
    for name, fsize in sizes:
        if name not in seen:
            seen.add(name)
            sizes_dedup.append((name, fsize))

    config = f'''# Paper Mario (US 1.0) N64Recomp generation config.
# Generated by scripts/generate-n64recomp-config.py from the decomp ELF.
# Paths are absolute so generation is cwd-independent.

[input]
entrypoint = 0x80025C00
elf_path = "{ELF}"
rom_file_path = "{ROM}"
output_func_path = "{ROOT / "generated/aot/paper_mario_recomp_out"}"
recomp_include = "#include <stdio.h>\\n#include \\"recomp.h\\""
unpaired_lo16_warnings = false

# Zero-sized global functions: size inferred from the next symbol in section.
{chr(10).join(f'[[input.function_sizes]]\nname = "{name}"\nsize = 0x{fsize:X}' for name, fsize in sizes_dedup)}

[patches]
renamed = [
    # The game ships its own libultra/libc variants of these; rename them so
    # the generated code does not collide with the host C library.
    "atan2",
    "printf",
]

# N64 OS exception handlers are never reached by native recompiled code; the
# runtime owns exception handling. __osException* are already reimplemented by
# N64Recomp's built-in list, so only handle_CPU needs an explicit stub to avoid
# recompiling shared exception-preamble code with out-of-function branches.
stubs = [
    "handle_CPU",
]

# Dead/uncompiled functions are never called and must not be recompiled.
ignored = [
    # RSP microcode embedded as "text": recompiled separately (audio via
    # RSPRecomp, graphics via the renderer's RSP handling).
    "n_aspMainTextStart",
    "n_aspMainTextEnd",
    "gspF3DZEX2_NoN_PosLight_fifoTextStart",
    "gspF3DZEX2_NoN_PosLight_fifoTextEnd",
# Shared OS exception-preamble body; only reachable from reimplemented
# __osException* handlers and manipulates cop0 registers directly.
"func_8006AA34",
    # IPL3/RSP boot microcode (0xA4000000 region). The CPU boot is replaced by
    # recomp_entrypoint; RSP boot microcode is handled by the runtime.
    "func_A4000040",
    "func_A40004C0",
    "func_A400076C",
    "func_A4000874",
    "func_A4000900",
    "func_A4000974",
    "func_A4000A34",
    "func_A4000AC4",
{chr(10).join(f'    "{name}",' for name in ignores)}
]

# The N64 idle thread is a tight spin loop (interrupts preempt it on real
# hardware). In the recomp runtime the VI/retrace messages arrive through
# pause_self, so inject a cooperative yield into the spin so boot progress
# (nuGfxRetraceWait) is never starved.
[[patches.hook]]
func = "boot_idle"
before_vram = 0x8005E98C
text = "yield_self_1ms(rdram);"

[[patches.hook]]
func = "nuGfxTaskAllEndWait"
before_vram = 0x8005F2D8
text = "yield_self_1ms(rdram);"


[[patches.hook]]
func = "nuGfxTaskMgrInit"
before_vram = 0x8002CB84
text = "fprintf(stderr, \\"[spool] init: 0x%X\\\\n\\", (unsigned)(uint32_t)ctx->r2);"

[[patches.hook]]
func = "nuGfxTaskStart"
before_vram = 0x8002CDE4
text = "fprintf(stderr, \\"[spool] start inc -> 0x%llX\\\\n\\", (unsigned long long)ctx->r3);"

[[patches.hook]]
func = "nuGfxTaskMgr"
before_vram = 0x8002CB30
text = "fprintf(stderr, \\"[spool] mgr dec -> 0x%llX\\\\n\\", (unsigned long long)ctx->r3);"

[[patches.hook]]
func = "nuGfxTaskMgr"
before_vram = 0x8002CAA8
text = "fprintf(stderr, \\"[mgr] msg=0x%llX task=0x%llX\\\\n\\", (unsigned long long)ctx->r2, (unsigned long long)ctx->r4);"

# Anti-piracy obfuscation wrappers read cartridge hardware (PI status and
# seed regions) that the recomp runtime does not model. They only exist to
# derive pointers to the real functions, so patch them into direct tail calls.
[[patches.instruction]]
func = "create_audio_system_obfuscated"
vram = 0x80200000
value = 0x08012AC0  # j create_audio_system (0x8004AB00)

[[patches.instruction]]
func = "create_audio_system_obfuscated"
vram = 0x80200004
value = 0x00000000  # nop

[[patches.instruction]]
func = "load_engine_data_obfuscated"
vram = 0x80200080
value = 0x08009B77  # j load_engine_data (0x80026DDC)

[[patches.instruction]]
func = "load_engine_data_obfuscated"
vram = 0x80200084
value = 0x00000000  # nop
'''
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(config)
    print(f"Wrote {OUT} with {len(sizes_dedup)} function sizes and {len(ignores)} dead-function ignores.")

if __name__ == "__main__":
    main()
