# Source-archive builds use previously hash-verified downloads only.
if(NOT COMMAND paperpad_offline_marker)
    function(paperpad_offline_marker)
    endfunction()
    macro(file)
        if("${ARGV0}" STREQUAL "DOWNLOAD")
            if(NOT EXISTS "${ARGV2}")
                message(FATAL_ERROR "Offline source archive lacks download: ${ARGV2}")
            endif()
            set(options ${ARGV})
            list(FIND options "EXPECTED_HASH" hash_index)
            if(NOT hash_index EQUAL -1)
                math(EXPR hash_index "${hash_index}+1")
                list(GET options ${hash_index} expected)
                _file(SHA256 "${ARGV2}" actual)
                if(NOT expected STREQUAL "SHA256=${actual}")
                    message(FATAL_ERROR "Offline download hash mismatch: ${ARGV2}")
                endif()
            endif()
            list(FIND options "STATUS" status_index)
            if(NOT status_index EQUAL -1)
                math(EXPR status_index "${status_index}+1")
                list(GET options ${status_index} status_variable)
                set(${status_variable} "0;verified local archive input")
            endif()
        else()
            _file(${ARGV})
        endif()
            endforeach()
        endif()
    endmacro()
endif()
