# Archive-only adapter: keep verified downloads, reject every missing download.
# Other file() calls are forwarded with argument boundaries preserved.
if(NOT COMMAND paperpad_offline_marker)
    function(paperpad_offline_marker)
    endfunction()
    function(file)
        if(ARGV0 STREQUAL "DOWNLOAD")
            if(NOT EXISTS "${ARGV2}")
                message(FATAL_ERROR "Offline source archive lacks download: ${ARGV2}")
            endif()
            set(_pp_args ${ARGV})
            list(FIND _pp_args "EXPECTED_HASH" _pp_index)
            if(NOT _pp_index EQUAL -1)
                math(EXPR _pp_index "${_pp_index}+1")
                list(GET _pp_args ${_pp_index} _pp_expected)
                _file(SHA256 "${ARGV2}" _pp_actual)
                if(NOT _pp_expected STREQUAL "SHA256=${_pp_actual}")
                    message(FATAL_ERROR "Offline download hash mismatch: ${ARGV2}")
                endif()
            endif()
            list(FIND _pp_args "STATUS" _pp_index)
            if(NOT _pp_index EQUAL -1)
                math(EXPR _pp_index "${_pp_index}+1")
                list(GET _pp_args ${_pp_index} _pp_result)
                set(${_pp_result} "0;verified local archive input" PARENT_SCOPE)
            endif()
        else()
            set(_pp_call "_file(")
            math(EXPR _pp_last "${ARGC}-1")
            foreach(_pp_index RANGE 0 ${_pp_last})
                set(_pp_arg "${ARGV${_pp_index}}")
                set(_pp_delimiter "=")
                while(_pp_arg MATCHES "\\]${_pp_delimiter}\\]")
                    string(APPEND _pp_delimiter "=")
                endwhile()
                string(APPEND _pp_call " [${_pp_delimiter}[${_pp_arg}]${_pp_delimiter}]")
            endforeach()
            cmake_language(EVAL CODE "${_pp_call})")
            get_cmake_property(_pp_variables VARIABLES)
            foreach(_pp_variable ${_pp_variables})
                if(NOT _pp_variable MATCHES "^(_pp_|ARG|CMAKE_CURRENT_FUNCTION)")
                    set(${_pp_variable} "${${_pp_variable}}" PARENT_SCOPE)
                endif()
            endforeach()
        endif()
    endfunction()
endif()
